Repository Team-Trit/donworry-ios, pull requests merged in 2022-09, with the labels that each got.

#182 AppIcon 변경 및 누락된 asset 추가
  Projects/DesignSystem/Resources/Asset.xcassets/ic_cash_coin.imageset/Contents.json
  Projects/DesignSystem/Resources/Asset.xcassets/ic_cash_coin.imageset/ic_cash_coin.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Projects/DonWorry/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/DonWorry/Sources/UI/JoinSpace/JoinSpaceViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardDeco/PaymentCardDecoViewController.swift
Labels: 🎄 AVERY

#191 :adhesive_bandage: 닉네임글자수제한 및 받을돈ui수정
  Projects/DesignSystem/Sources/TextField/LimitTextField.swift
  Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/Views/RecievedMoneyTableViewCell.swift
Labels: 🐞 bug, 🏝 YOUTH

#195 ♻️ UI 버그 수정 (노치없는기기 및 SE대응)
  Projects/Core/DonWorryExtensions/Sources/UIDevice+Utils.swift
  Projects/Core/DonWorryExtensions/Sources/UIWindow+Utils.swift
  Projects/DonWorry/Sources/Global/Toast/DWToastFactory.swift
  Projects/DonWorry/Sources/UI/ParticipatePaymentCard/ParticipatePaymentCardViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardDeco/PaymentCardDecoViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardIconEdit/PaymentCardIconEditViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardNameEdit/PaymentCardNameEditViewController.swift
  Projects/DonWorry/Sources/UI/Profile/ProfileViewController.swift
  Projects/DonWorry/Sources/UI/Profile/Views/AccountButtonStackView.swift
  Projects/DonWorry/Sources/UI/ProfileEditView/AcountEdit/AccountEditViewController.swift
  Projects/DonWorry/Sources/UI/ProfileEditView/NicknameEdit/NicknameEditViewController.swift
  Projects/DonWorry/Sources/UI/SpaceName/SpaceNameReactor.swift
  Projects/DonWorry/Sources/UI/SpaceName/SpaceNameViewController.swift
  Projects/DonWorry/SupportingFiles/DonWorry-Info.plist
  Projects/DonWorryNetworking/Sources/DTO/TestUserDTO.swift
Labels: WIP

#197 🐛 🚀 QA 2차 적용
  Projects/DonWorry/Project.swift
  Projects/DonWorry/Sources/App/AppDelegate.swift
  Projects/DonWorry/Sources/App/SceneDelegate.swift
  Projects/DonWorry/Sources/Domain/Auth/Model/AuthModels.swift
  Projects/DonWorry/Sources/Domain/Auth/Repository/AuthRepository.swift
  Projects/DonWorry/Sources/Domain/Auth/Repository/FCMDeviceTokenRepository.swift
  Projects/DonWorry/Sources/Domain/Auth/UseCase/DeRegisterUseCase.swift
  Projects/DonWorry/Sources/Domain/Auth/UseCase/LogoutUseCase.swift
  Projects/DonWorry/Sources/Domain/Auth/UseCase/SignInUseCase.swift
  Projects/DonWorry/Sources/Domain/Auth/UseCase/SignUpUseCase.swift
  Projects/DonWorry/Sources/Domain/Payment/Repository/PaymentRepository.swift
  Projects/DonWorry/Sources/Domain/Space/Error/SpaceError.swift
  Projects/DonWorry/Sources/Domain/Space/Models/SpaceModels.swift
  Projects/DonWorry/Sources/Domain/Space/Repository/SpaceRepository.swift
  Projects/DonWorry/Sources/Domain/Space/Service/SpaceService.swift
  Projects/DonWorry/Sources/Global/Extensions/UIImageView+BasicProfile.swift
  Projects/DonWorry/Sources/UI/Auth/Login/LoginViewReactor.swift
  Projects/DonWorry/Sources/UI/Home/Cells/SpaceCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/TakeBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/HomePresenter.swift
  Projects/DonWorry/Sources/UI/Home/HomeReactor.swift
  Projects/DonWorry/Sources/UI/Home/HomeViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardDeco/Cell/FilePicker/Cell/PhotoCell.swift
  Projects/DonWorry/Sources/UI/PaymentCardDetail/Views/DetailImageViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardDetail/Views/FileCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/Cells/AddPaymentCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListReactor.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
  Projects/DonWorry/Sources/UI/Profile/ProfileViewController.swift
  Projects/DonWorry/Sources/UI/Profile/ProfileViewReactor.swift
  Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/ReceivedMoneyDetailReactor.swift
  Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/Views/RecievedMoneyTableViewCell.swift
  Projects/DonWorry/SupportingFiles/DonWorry-Info.plist
  Projects/DonWorry/SupportingFiles/DonWorry.entitlements
  Projects/DonWorryLocalStorage/Sources/UserDefaultsKey.swift
  Projects/DonWorryNetworking/Sources/APIs/Space/GetSpaceAPI.swift
  Projects/DonWorryNetworking/Sources/APIs/User/AppleLoginAPI.swift
  Projects/DonWorryNetworking/Sources/APIs/User/AppleRegisterAPI.swift
  Projects/DonWorryNetworking/Sources/APIs/User/DeregisterAPI.swift
  Projects/DonWorryNetworking/Sources/APIs/User/KakaoLoginAPI.swift
  Projects/DonWorryNetworking/Sources/APIs/User/KakaoRegisterAPI.swift
  Projects/DonWorryNetworking/Sources/APIs/User/LogoutAPI.swift
  Projects/DonWorryNetworking/Sources/DTO/GetPaymentsGiverDTO.swift
Labels: Quick Merge, no review

#198 🔮 UI 버그 수정 및 홈 카드 애니메이션 추가
  Projects/Core/DonWorryExtensions/Sources/UIView+Utils.swift
  Projects/DesignSystem/Sources/Button/DWBaseButton.swift
  Projects/DesignSystem/Sources/NavigationBar/DWNavigationBar.swift
  Projects/DonWorry/Sources/UI/Home/Cells/GiveBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/LeaveSpaceBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/StateBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/TakeBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/HomeViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/Cells/AddPaymentCardCollectionViewCell.swift
Labels: Quick Merge, no review

#199 🐞 홈 카드 애니메이션 제거
  Projects/DonWorry/Sources/UI/Home/Cells/GiveBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/LeaveSpaceBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/StateBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/Cells/TakeBillCardCollectionViewCell.swift
  Projects/DonWorry/Sources/UI/Home/HomeViewController.swift
Labels: 🐞 bug

#201 :bug: 서버에서 이미지 못불러오는 버그 수정
  Projects/DonWorry/Sources/UI/SentMoneyDetail/Views/SentMoneyTableViewCell.swift
Labels: 🐞 bug, 🏝 YOUTH

#203 🔮AmountEditView 오토레이아웃 전체 기기 대응
  Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/PaymentCardAmountEditViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/Views/NumberPadCollectionView.swift
Labels: 🐞 bug, 🎄 AVERY, Quick Merge, no review
