Repository Team-Trit/donworry-ios, pull requests merged in 2022-10, with the labels that each got.

#233 ✨카드 금액 수정 기능 추가
  Projects/DonWorry/Sources/Domain/PaymentCard/Model/PaymentCardModels.swift
  Projects/DonWorry/Sources/Domain/PaymentCard/Repository/PaymentCardRepository.swift
  Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/PaymentCardAmountEditReactor.swift
  Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/PaymentCardAmountEditViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewReactor.swift
  Projects/DonWorryNetworking/Sources/DTO/GetPaymentCardDTO.swift
Labels: enhancement, 🎹 CHARLIE

#234 ♻️카드리스트, 참석확인 페이지 UI 수정, 카드 아이콘 추가
  Projects/DesignSystem/Resources/Asset.xcassets/btn_copy.imageset/Contents.json
  Projects/DesignSystem/Resources/Asset.xcassets/btn_copy.imageset/btn_copy.png
  Projects/DesignSystem/Resources/Asset.xcassets/btn_copy.imageset/btn_copy@2x.png
  Projects/DesignSystem/Resources/Asset.xcassets/btn_copy.imageset/btn_copy@3x.png
  Projects/DesignSystem/Resources/Asset.xcassets/ic_bacon.imageset/Contents.json
  Projects/DesignSystem/Resources/Asset.xcassets/ic_bacon.imageset/ic_bacon.png
  Projects/DesignSystem/Resources/Asset.xcassets/ic_beer.imageset/Contents.json
  Projects/DesignSystem/Resources/Asset.xcassets/ic_beer.imageset/ic_beer.png
  Projects/DesignSystem/Resources/Asset.xcassets/ic_mic.imageset/Contents.json
  Projects/DesignSystem/Resources/Asset.xcassets/ic_mic.imageset/ic_mic.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Button/DWButton.swift
  Projects/DonWorry/Sources/UI/ParticipatePaymentCard/ParticipatePaymentCardViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
Labels: 🎹 CHARLIE

#235 카테고리 아이콘추가에 따른 반응형 대응 및 카드리스트 always-scrollable
  Projects/Core/DonWorryExtensions/Sources/UIScreen+Utils.swift
  Projects/DonWorry/Sources/UI/PaymentCardIconEdit/PaymentCardIconEditViewController.swift
  Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
Labels: 🐞 bug, 🎄 AVERY
